name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build twine

    - name: Run full test suite
      run: |
        pip install pytest pytest-cov pytest-asyncio
        pytest tests/ -v --cov=tools --cov=utils

    - name: Build package
      run: |
        python -m build

    - name: Create Release Notes
      run: |
        echo "# Water Chemistry MCP Server Release ${{ github.ref_name }}" > release_notes.md
        echo "" >> release_notes.md
        echo "## Features" >> release_notes.md
        echo "- Advanced water chemistry modeling with PHREEQC integration" >> release_notes.md
        echo "- Kinetic and equilibrium precipitation modeling" >> release_notes.md
        echo "- Industrial wastewater treatment design tools" >> release_notes.md
        echo "- Engineering calculation sheet generation" >> release_notes.md
        echo "" >> release_notes.md
        echo "## Installation" >> release_notes.md
        echo "\`\`\`bash" >> release_notes.md
        echo "pip install -r requirements.txt" >> release_notes.md
        echo "python server.py" >> release_notes.md
        echo "\`\`\`" >> release_notes.md

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Water Chemistry MCP Server ${{ github.ref_name }}
        body_path: release_notes.md
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/water-chemistry-mcp-${{ github.ref_name }}.tar.gz
        asset_name: water-chemistry-mcp-${{ github.ref_name }}.tar.gz
        asset_content_type: application/gzip
      continue-on-error: true